### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by gingdotgithub** [Hackathons-UK/wiki#153]
theres some dead links in /docs/index.md (typically missing .md and 404ing)

**Comment by wrussell1999** [comment]
Hey! Could you point us to which ones please? :D

**Comment by gingdotgithub** [comment]
hey sorry. e.g. on https://github.com/Hackathons-UK/wiki/blob/master/docs/index.md the 'attend' and 'organise' links at the top 404 - and a couple of the others link to a folder of the repo rather than a markdown (which i think its supposed to).

**Comment by ksouthern** [comment]
They seem fine on the live site, the only issue seems to be that it doesn't link within the repo.
If we were to change it so it works within the repo, then it wouldn't work on the live site.
