### ISSUE TITLE
Add an event Pull Request Template

### ISSUE THREAD

**Issue by aaronosher** [Hackathons-UK/wiki#198]

**Comment by Tello-Wharton** [comment]
Mm? Is this closed because of the events.yml? I feel like this isn't "done" until we've documented the tags, how to use each field etc... 

part done :) 

Perhaps we could make a more descriptive issue?

**Comment by bahorn** [comment]
This is about https://github.com/Hackathons-UK/wiki/pull/205

**Comment by Tello-Wharton** [comment]
Ah, my mistake, close away!
