### ISSUE TITLE
No spacing between content and left edge of body

### ISSUE THREAD

**Issue by robzwolf** [Hackathons-UK/wiki#206]
The words `Autumn 2020`, along with other elements on the page, are too close to the left-hand side of the window. Some padding or a margin needs to be added here. 

![IMG_0943](https://user-images.githubusercontent.com/5098748/87887424-07af1b00-ca1d-11ea-8cbc-9949443dd7db.png)

**Comment by bahorn** [comment]
Yep! Forgot I needed to do that!

**Comment by bahorn** [comment]
#208 should fix this
