### ISSUE TITLE
Moving some of the tables out of the markdown

### ISSUE THREAD

**Issue by bahorn** [Hackathons-UK/wiki#38]
The list of events and Society GitHub organisations should probably be moved into something like a CSV and then just merged into the document during the build.

This would make it much easier for projects to work off our data and also make maintaining much easier.

Ties somewhat into #17 and would definitely make it easier to resolve that.

**Comment by ksouthern** [comment]
The HackNotts hack I did with @Hammie217 used the events table and converted it into a 2D array, I'm currently working on editing it so that it converts it into XML or JSON or something similar.

**Comment by bahorn** [comment]
Got the list of events in a more useful form now:

https://gist.github.com/bahorn/bb953987edf0ffd4aed2c69a2988612e
